spring:
  application:
    name: ecommerce-userservice
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=usersdb;encrypt=false
    username: Aditya
    password: Adiboy@9921

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
  server:
    servlet:
      context:
        path: /user-service/api/
